# Generated by Django 4.2 on 2023-04-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('classname', models.CharField(max_length=1000)),
                ('fathername', models.CharField(max_length=1000)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
